---
title: "Using nVennR to generate and explore n-dimensional, quasi-proportional Venn diagrams"
author: "Victor Quesada"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    toc: true
vignette: >
  %\VignetteIndexEntry{Using nVennR to generate and explore n-dimensional, quasi-proportional Venn diagrams}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---


nVennR provides an R interface to the [nVenn algorithm](https://academic.oup.com/bioinformatics/article/34/13/2322/4904268). This vignette intends to illustrate three basic uses of nVennR:

* Create Venn and Euler diagrams
* Generate and customize high-quality figures to depict the diagram
* Explore the regions of the diagram

## Create diagrams
There are two ways to create a Venn diagram object (`nVennObj`), which will be referenced as high-level (by providing intersecting lists) and low-level (from scratch).

### High-level

The most common use for a package like nVennR is to depict the relationships between several intersecting lists. The main function for this task is `plotVenn`. The input is a list of vectors (or lists) describing each set. The name of each inner vector will be used for labeling. If inner vectors are not named, labels can be provided as a vector with `sNames`. Empty names will be filled with `GroupN`. Examples:

```{r "plotVenn"}
library(nVennR)
exampledf
sas <- subset(exampledf, SAS == "Y")$Employee
python <- subset(exampledf, Python == "Y")$Employee
rr <- subset(exampledf, R == "Y")$Employee
myV <- plotVenn(list(SAS=sas, PYTHON=python, R=rr), nCycles = 2000)

```
