# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

drawVenn <- function(x) {
    .Call('_nVennR_drawVenn', PACKAGE = 'nVennR', x)
}

makeVenn <- function(x, nCycl) {
    .Call('_nVennR_makeVenn', PACKAGE = 'nVennR', x, nCycl)
}

refineVenn <- function(x) {
    .Call('_nVennR_refineVenn', PACKAGE = 'nVennR', x)
}

